[package]
name = "jclulow1"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
cortexm3 = { path = "../../arch/cortex-m3" }
tock_rt0 = { path = "../../libraries/tock-rt0" }
kernel = { path = "../../kernel" }
